package team161;

public enum Action {
	
	SEE_ART, KILLING, RUSH, DISTRESS, GEN_SUP, CAP_SUP, CAP_GEN, CAP_ART, CAP_MED, CAP_SHIELD, CAPTURING, GO_TO_ENCAMP, ENEMY, RALLY_AT, CAP, DEFUSING, ATTACK, DONT_CAP;

}
